# Generated by Django 4.1 on 2023-03-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(default=datetime.date.today)),
                ('Mood_Choice', models.CharField(choices=[('HPY', 'Happy'), ('SAD', 'Sad'), ('TRD', 'Tired'), ('ANG', 'Angry'), ('EXC', 'Excited')], default='HPY', max_length=3)),
            ],
        ),
    ]
