# Generated by Django 4.1 on 2023-03-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_moods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moods',
            old_name='dob',
            new_name='date',
        ),
    ]
