# Generated by Django 4.1 on 2023-03-08 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_dob_moods_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=500)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=254)),
                ('exam_date', models.DateField(default=datetime.date.today)),
                ('exam_type', models.CharField(choices=[('FNL', 'Final Exam'), ('MTM', 'Midterm'), ('TRM', 'Termtime Exam'), ('QUZ', 'Quiz/MCQ')], default='FNL', max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='moods',
            old_name='Mood_Choice',
            new_name='mood_choice',
        ),
    ]
