# Generated by Django 4.1 on 2023-03-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_assignments_assignment_rename_exams_exam_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='description',
            new_name='assignment_desc',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='title',
            new_name='assignment_title',
        ),
    ]
