# Generated by Django 4.1 on 2023-03-09 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_rename_description_assignment_assignment_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mood',
            old_name='date',
            new_name='mood_date',
        ),
    ]
