# Generated by Django 4.1 on 2023-03-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
