# Generated by Django 4.1 on 2023-03-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_alter_exam_exam_type_alter_mood_mood_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='due_date',
            new_name='assignment_due_date',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_status',
            field=models.BooleanField(default=False),
        ),
    ]
