# Generated by Django 4.1 on 2023-04-06 18:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_alter_assignment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_desc',
            field=models.CharField(max_length=750),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_company', models.CharField(max_length=254)),
                ('application_deadline', models.DateField(default=datetime.date.today)),
                ('application_type', models.CharField(choices=[('Graduate Job', 'Graduate Job'), ('Internship', 'Internship'), ('Other', 'Other Type')], default='Graduate Job', max_length=15)),
                ('application_notes', models.CharField(max_length=750)),
                ('application_status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
